name: ilayda-test-hello
base: core22
version: '1.0.3'
summary: A trivial snap app
description: Just prints hello

grade: stable
confinement: strict

apps:
  ilayda-test-hello:
    command: usr/bin/hello.py

parts:
  ilayda-test-hello:
    plugin: dump
    source: .
    stage-packages:
      - python3

